version: '3.0'

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
        - high

scanning-settings:
  max-depth: 6
  exclude:
    - "node_modules"
    - "venv"
    - ".venv"
    - "env"
    - ".env"
    - "tests/**"
    - "test/**"
    - "**/*.test.py"
    - "**/__pycache__"
    - ".git"
    - "build"
    - "dist"
    - "*.egg-info"
